version: "3"

services:
  backend:
    build: ./dockercompose
    ports:
      - "8000:8000"

  http-request:
    build: ./httprequest

  logdb:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pglogdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logdb

  adminer:
    image: adminer
    depends_on:
      - logdb
    ports:
      - "8080:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  pglogdb:
